In [40]:
import requests
from lxml.html import fromstring
import pandas as pd

In [2]:
response = requests.get('https://free-proxy-list.net/')
parser = fromstring(response.text)
parser.xpath('/*')

In [8]:
table = parser.xpath('//*[@id="list"]/div/div[2]/div/table')

In [16]:
rows = parser.xpath('//*[@id="list"]/div/div[2]/div/table//tr')

In [35]:
columns = rows[0].xpath('.//text()')

In [38]:
data = []
for row in rows[1:]:
    data.append(row.xpath('.//text()'))

In [41]:
pd.DataFrame(data=data, columns=columns)

,IP Address,Port,Code,Country,Anonymity,Google,Https,Last Checked
0,47.74.71.208,8080,AU,Australia,elite proxy,no,2 secs ago,None
1,45.229.205.106,55555,AR,Argentina,elite proxy,no,2 secs ago,None
2,182.160.16.163,20002,SG,Singapore,elite proxy,no,2 secs ago,None
3,66.70.178.214,9300,CA,Canada,elite proxy,no,2 secs ago,None
4,103.152.232.84,8080,ID,Indonesia,anonymous,no,2 secs ago,None
...,...,...,...,...,...,...,...,...
295,154.92.123.192,5530,RO,Romania,transparent,no,no,14 mins ago
296,154.92.123.127,5465,RO,Romania,transparent,no,no,14 mins ago
297,176.116.230.66,7152,RO,Romania,transparent,no,no,14 mins ago
298,167.71.209.253,80,SG,Singapore,transparent,no,no,14 mins ago
299,154.92.121.105,5124,RO,Romania,transparent,no,no,14 mins ago